import React from 'react';
import {StyleSheet} from 'react-native';
import {NavigationProp} from '@react-navigation/core';

import Container, {StatusBarStyle} from '../components/Container';
import CategoryList from '../components/categories/categoryList';
import {getWidth} from '../utils/interfaceDimentions';

interface IProps {
  navigation: NavigationProp<any, any>;
}

const Categories: React.FC<IProps> = ({navigation}) => {
  return (
    <Container
      containerStyles={styles.container}
      statusBarStyle={StatusBarStyle.DARK}>
      <CategoryList data={dummy.children_data} />
    </Container>
  );
};

const styles = StyleSheet.create({
  container: {
    paddingLeft: getWidth(24),
    paddingRight: getWidth(24),
  },
});

export default Categories;

const dummy = {
  id: 87,
  parent_id: 2,
  name: 'Categorías',
  is_active: true,
  position: 1,
  level: 2,
  product_count: 12363,
  children_data: [
    {
      id: 205,
      parent_id: 87,
      name: 'Cocina',
      is_active: true,
      position: 1,
      level: 3,
      product_count: 3486,
      children_data: [
        {
          id: 208,
          parent_id: 205,
          name: 'Utensilios de Cocina',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 939,
          children_data: [
            {
              id: 214,
              parent_id: 208,
              name: 'Básicos de Cocina',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 304,
              children_data: [],
            },
            {
              id: 445,
              parent_id: 208,
              name: 'Accesorios de Cocina',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 102,
              children_data: [],
            },
            {
              id: 442,
              parent_id: 208,
              name: 'Repostería',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 94,
              children_data: [],
            },
            {
              id: 217,
              parent_id: 208,
              name: 'Moldes y Charolas',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 135,
              children_data: [],
            },
            {
              id: 211,
              parent_id: 208,
              name: 'Cortadores y Peladores',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 89,
              children_data: [],
            },
            {
              id: 220,
              parent_id: 208,
              name: 'Tablas para Picar',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 44,
              children_data: [],
            },
            {
              id: 439,
              parent_id: 208,
              name: 'Medidores y Termómetros',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 48,
              children_data: [],
            },
            {
              id: 646,
              parent_id: 208,
              name: 'Gadgets de Cocina',
              is_active: true,
              position: 9,
              level: 5,
              product_count: 103,
              children_data: [],
            },
          ],
        },
        {
          id: 448,
          parent_id: 205,
          name: 'Electrodomésticos',
          is_active: true,
          position: 2,
          level: 4,
          product_count: 180,
          children_data: [
            {
              id: 451,
              parent_id: 448,
              name: 'Hornos',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 12,
              children_data: [],
            },
            {
              id: 454,
              parent_id: 448,
              name: 'Licuadoras',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 10,
              children_data: [],
            },
            {
              id: 457,
              parent_id: 448,
              name: 'Procesadores de Alimentos',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 9,
              children_data: [],
            },
            {
              id: 460,
              parent_id: 448,
              name: 'Extractores',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 8,
              children_data: [],
            },
            {
              id: 463,
              parent_id: 448,
              name: 'Freidoras y Vaporeras',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 2,
              children_data: [],
            },
            {
              id: 466,
              parent_id: 448,
              name: 'Especializados',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 32,
              children_data: [],
            },
            {
              id: 469,
              parent_id: 448,
              name: 'Tostadores',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 5,
              children_data: [],
            },
            {
              id: 472,
              parent_id: 448,
              name: 'Batidoras',
              is_active: true,
              position: 8,
              level: 5,
              product_count: 21,
              children_data: [],
            },
            {
              id: 475,
              parent_id: 448,
              name: 'Café y Té',
              is_active: true,
              position: 9,
              level: 5,
              product_count: 81,
              children_data: [],
            },
          ],
        },
        {
          id: 496,
          parent_id: 205,
          name: 'Baterías de Cocina',
          is_active: true,
          position: 3,
          level: 4,
          product_count: 180,
          children_data: [
            {
              id: 499,
              parent_id: 496,
              name: 'Ollas y Sartenes',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 144,
              children_data: [],
            },
            {
              id: 502,
              parent_id: 496,
              name: 'Sets de Ollas y Sartenes',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 36,
              children_data: [],
            },
          ],
        },
        {
          id: 478,
          parent_id: 205,
          name: 'Organización de Cocina',
          is_active: true,
          position: 4,
          level: 4,
          product_count: 985,
          children_data: [
            {
              id: 481,
              parent_id: 478,
              name: 'Contenedores de Alimentos',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 274,
              children_data: [],
            },
            {
              id: 643,
              parent_id: 478,
              name: 'Organizadores de Cocina',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 134,
              children_data: [],
            },
            {
              id: 484,
              parent_id: 478,
              name: 'Dispensadores',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 27,
              children_data: [],
            },
            {
              id: 487,
              parent_id: 478,
              name: 'Almacenamiento y Limpieza',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 374,
              children_data: [],
            },
            {
              id: 490,
              parent_id: 478,
              name: 'Alacena',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 99,
              children_data: [],
            },
            {
              id: 493,
              parent_id: 478,
              name: 'Vinos y Cervezas',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 71,
              children_data: [],
            },
          ],
        },
        {
          id: 520,
          parent_id: 205,
          name: 'Mesa',
          is_active: true,
          position: 5,
          level: 4,
          product_count: 353,
          children_data: [
            {
              id: 1186,
              parent_id: 520,
              name: 'Mantelería y Accesorios de Mesa',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 353,
              children_data: [],
            },
          ],
        },
        {
          id: 505,
          parent_id: 205,
          name: 'Cubertería Cristalería y Vajillas',
          is_active: true,
          position: 6,
          level: 4,
          product_count: 852,
          children_data: [
            {
              id: 508,
              parent_id: 505,
              name: 'Cuchillos',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 125,
              children_data: [],
            },
            {
              id: 511,
              parent_id: 505,
              name: 'Cubiertos',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 119,
              children_data: [],
            },
            {
              id: 514,
              parent_id: 505,
              name: 'Vajillas',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 250,
              children_data: [],
            },
            {
              id: 523,
              parent_id: 505,
              name: 'Jarras',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 40,
              children_data: [],
            },
            {
              id: 1189,
              parent_id: 505,
              name: 'Vasos y Tarros',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 219,
              children_data: [],
            },
            {
              id: 1192,
              parent_id: 505,
              name: 'Copas',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 92,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 226,
      parent_id: 87,
      name: 'Recámara',
      is_active: true,
      position: 2,
      level: 3,
      product_count: 1601,
      children_data: [
        {
          id: 229,
          parent_id: 226,
          name: 'Ropa de cama',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 906,
          children_data: [
            {
              id: 232,
              parent_id: 229,
              name: 'Sábanas',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 117,
              children_data: [],
            },
            {
              id: 235,
              parent_id: 229,
              name: 'Edredones',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 75,
              children_data: [],
            },
            {
              id: 238,
              parent_id: 229,
              name: 'Cobijas Frazadas y Mantas',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 118,
              children_data: [],
            },
            {
              id: 241,
              parent_id: 229,
              name: 'Sets de Cama',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 383,
              children_data: [],
            },
            {
              id: 244,
              parent_id: 229,
              name: 'Cobertores y Colchas',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 164,
              children_data: [],
            },
            {
              id: 526,
              parent_id: 229,
              name: 'Rodapiés',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 35,
              children_data: [],
            },
            {
              id: 529,
              parent_id: 229,
              name: 'Accesorios de Cama',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 15,
              children_data: [],
            },
          ],
        },
        {
          id: 532,
          parent_id: 226,
          name: 'Almohadas',
          is_active: true,
          position: 2,
          level: 4,
          product_count: 87,
          children_data: [
            {
              id: 535,
              parent_id: 532,
              name: 'Almohadas Estándar',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 23,
              children_data: [],
            },
            {
              id: 541,
              parent_id: 532,
              name: 'Almohadas Queen Size',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 2,
              children_data: [],
            },
            {
              id: 538,
              parent_id: 532,
              name: 'Almohadas King Size',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 13,
              children_data: [],
            },
            {
              id: 544,
              parent_id: 532,
              name: 'Almohadas Tamaño Europeo',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 2,
              children_data: [],
            },
            {
              id: 547,
              parent_id: 532,
              name: 'Almohadas Especiales',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 44,
              children_data: [],
            },
          ],
        },
        {
          id: 550,
          parent_id: 226,
          name: 'Cojines',
          is_active: true,
          position: 3,
          level: 4,
          product_count: 85,
          children_data: [
            {
              id: 553,
              parent_id: 550,
              name: 'Cojines Decorativos',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 83,
              children_data: [],
            },
          ],
        },
        {
          id: 556,
          parent_id: 226,
          name: 'Colchonetas',
          is_active: true,
          position: 4,
          level: 4,
          product_count: 56,
          children_data: [],
        },
        {
          id: 559,
          parent_id: 226,
          name: 'Fundas y Protectores',
          is_active: true,
          position: 5,
          level: 4,
          product_count: 466,
          children_data: [
            {
              id: 562,
              parent_id: 559,
              name: 'Fundas para Almohadas',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 200,
              children_data: [],
            },
            {
              id: 565,
              parent_id: 559,
              name: 'Fundas para Edredones',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 116,
              children_data: [],
            },
            {
              id: 568,
              parent_id: 559,
              name: 'Fundas para Cojines',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 44,
              children_data: [],
            },
            {
              id: 571,
              parent_id: 559,
              name: 'Protectores de Colchones',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 92,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 268,
      parent_id: 87,
      name: 'Baño',
      is_active: true,
      position: 3,
      level: 3,
      product_count: 2788,
      children_data: [
        {
          id: 427,
          parent_id: 268,
          name: 'Accesorios para Baño',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 1050,
          children_data: [
            {
              id: 640,
              parent_id: 427,
              name: 'Organizadores para Baño',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 160,
              children_data: [],
            },
            {
              id: 277,
              parent_id: 427,
              name: 'Jaboneras',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 101,
              children_data: [],
            },
            {
              id: 280,
              parent_id: 427,
              name: 'Portacepillos y Vasos',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 234,
              children_data: [],
            },
            {
              id: 286,
              parent_id: 427,
              name: 'Botes de Basura',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 125,
              children_data: [],
            },
            {
              id: 595,
              parent_id: 427,
              name: 'Toalleros',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 75,
              children_data: [],
            },
            {
              id: 598,
              parent_id: 427,
              name: 'Dispensadores de Jabón',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 149,
              children_data: [],
            },
            {
              id: 601,
              parent_id: 427,
              name: 'Dispensadores de Pañuelos',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 62,
              children_data: [],
            },
            {
              id: 604,
              parent_id: 427,
              name: 'Inodoro',
              is_active: true,
              position: 8,
              level: 5,
              product_count: 65,
              children_data: [],
            },
          ],
        },
        {
          id: 433,
          parent_id: 268,
          name: 'Toallas para Baño',
          is_active: true,
          position: 2,
          level: 4,
          product_count: 983,
          children_data: [
            {
              id: 574,
              parent_id: 433,
              name: 'Toallas de Baño',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 125,
              children_data: [],
            },
            {
              id: 577,
              parent_id: 433,
              name: 'Toallas de Medio Baño',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 245,
              children_data: [],
            },
            {
              id: 580,
              parent_id: 433,
              name: 'Toallas Faciales',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 157,
              children_data: [],
            },
            {
              id: 583,
              parent_id: 433,
              name: 'Toallas para Manos',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 230,
              children_data: [],
            },
            {
              id: 586,
              parent_id: 433,
              name: 'Toallas para Invitados',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 74,
              children_data: [],
            },
            {
              id: 589,
              parent_id: 433,
              name: 'Batas de Baño',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 12,
              children_data: [],
            },
            {
              id: 622,
              parent_id: 433,
              name: 'Toallas Fingertip',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 115,
              children_data: [],
            },
          ],
        },
        {
          id: 430,
          parent_id: 268,
          name: 'Tapetes para Baño',
          is_active: true,
          position: 3,
          level: 4,
          product_count: 405,
          children_data: [],
        },
        {
          id: 607,
          parent_id: 268,
          name: 'Muebles para Baño',
          is_active: true,
          position: 4,
          level: 4,
          product_count: 37,
          children_data: [],
        },
        {
          id: 619,
          parent_id: 268,
          name: 'Seguridad',
          is_active: true,
          position: 5,
          level: 4,
          product_count: 12,
          children_data: [
            {
              id: 649,
              parent_id: 619,
              name: 'Seguridad para Baño',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 12,
              children_data: [],
            },
          ],
        },
        {
          id: 610,
          parent_id: 268,
          name: 'Regadera y Tina',
          is_active: true,
          position: 6,
          level: 4,
          product_count: 329,
          children_data: [
            {
              id: 613,
              parent_id: 610,
              name: 'Cortinas de Baño',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 186,
              children_data: [],
            },
            {
              id: 616,
              parent_id: 610,
              name: 'Accesorios para Regadera y Tina',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 143,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 331,
      parent_id: 87,
      name: 'Organización y Limpieza',
      is_active: true,
      position: 4,
      level: 3,
      product_count: 1118,
      children_data: [
        {
          id: 334,
          parent_id: 331,
          name: 'Organizadores',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 518,
          children_data: [
            {
              id: 337,
              parent_id: 334,
              name: 'Joyería',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 17,
              children_data: [],
            },
            {
              id: 340,
              parent_id: 334,
              name: 'Maquillaje y Cabello',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 18,
              children_data: [],
            },
            {
              id: 343,
              parent_id: 334,
              name: 'Cestos y Canastas',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 66,
              children_data: [],
            },
            {
              id: 346,
              parent_id: 334,
              name: 'Cajas',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 34,
              children_data: [],
            },
            {
              id: 349,
              parent_id: 334,
              name: 'Bolsas',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 45,
              children_data: [],
            },
            {
              id: 652,
              parent_id: 334,
              name: 'Multiusos',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 148,
              children_data: [],
            },
            {
              id: 655,
              parent_id: 334,
              name: 'Percheros y Ganchos',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 174,
              children_data: [],
            },
          ],
        },
        {
          id: 658,
          parent_id: 331,
          name: 'Limpieza',
          is_active: true,
          position: 2,
          level: 4,
          product_count: 401,
          children_data: [
            {
              id: 661,
              parent_id: 658,
              name: 'Basura y Reciclaje',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 42,
              children_data: [],
            },
            {
              id: 664,
              parent_id: 658,
              name: 'Lavandería',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 33,
              children_data: [],
            },
            {
              id: 667,
              parent_id: 658,
              name: 'Aspiradoras',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 16,
              children_data: [],
            },
            {
              id: 670,
              parent_id: 658,
              name: 'Planchaduría',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 41,
              children_data: [],
            },
            {
              id: 673,
              parent_id: 658,
              name: 'Artículos y Utensilios de Limpieza',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 248,
              children_data: [],
            },
            {
              id: 676,
              parent_id: 658,
              name: 'Humificadores y Aromatizantes',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 20,
              children_data: [],
            },
          ],
        },
        {
          id: 679,
          parent_id: 331,
          name: 'Líquidos de Limpieza',
          is_active: true,
          position: 3,
          level: 4,
          product_count: 171,
          children_data: [
            {
              id: 682,
              parent_id: 679,
              name: 'Líquidos para Ropa y Telas',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 22,
              children_data: [],
            },
            {
              id: 685,
              parent_id: 679,
              name: 'Líquidos para Pisos',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 27,
              children_data: [],
            },
            {
              id: 688,
              parent_id: 679,
              name: 'Líquidos para Baño',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 25,
              children_data: [],
            },
            {
              id: 691,
              parent_id: 679,
              name: 'Líquidos Multiusos',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 61,
              children_data: [],
            },
            {
              id: 694,
              parent_id: 679,
              name: 'Líquidos para Cocina',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 33,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 247,
      parent_id: 87,
      name: 'Decoración',
      is_active: true,
      position: 5,
      level: 3,
      product_count: 1729,
      children_data: [
        {
          id: 250,
          parent_id: 247,
          name: 'Decoración del Hogar',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 1492,
          children_data: [
            {
              id: 253,
              parent_id: 250,
              name: 'Cortinas y Accesorios para Ventanas',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 517,
              children_data: [
                {
                  id: 2585,
                  parent_id: 253,
                  name: 'cortinas',
                  is_active: true,
                  position: 1,
                  level: 6,
                  product_count: 0,
                  children_data: [],
                },
              ],
            },
            {
              id: 256,
              parent_id: 250,
              name: 'Cuadros y Marcos',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 325,
              children_data: [],
            },
            {
              id: 718,
              parent_id: 250,
              name: 'Espejos de Pared',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 20,
              children_data: [],
            },
            {
              id: 721,
              parent_id: 250,
              name: 'Relojes de Pared',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 39,
              children_data: [],
            },
            {
              id: 2152,
              parent_id: 250,
              name: 'Velas y Difusores',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 494,
              children_data: [],
            },
          ],
        },
        {
          id: 259,
          parent_id: 247,
          name: 'Tapetes para el Hogar',
          is_active: true,
          position: 2,
          level: 4,
          product_count: 236,
          children_data: [
            {
              id: 727,
              parent_id: 259,
              name: 'Tapetes para Entrada',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 80,
              children_data: [],
            },
            {
              id: 724,
              parent_id: 259,
              name: 'Tapetes Decorativos',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 145,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 709,
      parent_id: 87,
      name: 'Muebles',
      is_active: true,
      position: 6,
      level: 3,
      product_count: 154,
      children_data: [
        {
          id: 712,
          parent_id: 709,
          name: 'Muebles para el Hogar',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 110,
          children_data: [],
        },
      ],
    },
    {
      id: 352,
      parent_id: 87,
      name: 'Cuidado Personal',
      is_active: true,
      position: 9,
      level: 3,
      product_count: 429,
      children_data: [
        {
          id: 730,
          parent_id: 352,
          name: 'Salud y Belleza',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 428,
          children_data: [
            {
              id: 733,
              parent_id: 730,
              name: 'Cuidado del Cabello',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 58,
              children_data: [],
            },
            {
              id: 736,
              parent_id: 730,
              name: 'Artículos de Belleza',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 70,
              children_data: [],
            },
            {
              id: 739,
              parent_id: 730,
              name: 'Cuidado Facial y Corporal',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 106,
              children_data: [],
            },
            {
              id: 742,
              parent_id: 730,
              name: 'Ejercicio',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 13,
              children_data: [],
            },
            {
              id: 745,
              parent_id: 730,
              name: 'Básculas',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 16,
              children_data: [],
            },
            {
              id: 1195,
              parent_id: 730,
              name: 'Artículos Personales',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 165,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 802,
      parent_id: 87,
      name: 'Tecnología',
      is_active: true,
      position: 10,
      level: 3,
      product_count: 131,
      children_data: [
        {
          id: 805,
          parent_id: 802,
          name: 'Tecnología para el Hogar',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 128,
          children_data: [
            {
              id: 811,
              parent_id: 805,
              name: 'Hogar Inteligente',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 111,
              children_data: [],
            },
            {
              id: 2053,
              parent_id: 805,
              name: 'Ventiladores y Calefactores',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 5,
              children_data: [],
            },
            {
              id: 2326,
              parent_id: 805,
              name: 'Ventiladores y Calentadores',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 3,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 394,
      parent_id: 87,
      name: 'Mascotas Viajes y más',
      is_active: true,
      position: 12,
      level: 3,
      product_count: 797,
      children_data: [
        {
          id: 397,
          parent_id: 394,
          name: 'Mascotas',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 237,
          children_data: [
            {
              id: 403,
              parent_id: 397,
              name: 'Alimentadores',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 38,
              children_data: [],
            },
            {
              id: 400,
              parent_id: 397,
              name: 'Camas',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 24,
              children_data: [],
            },
            {
              id: 412,
              parent_id: 397,
              name: 'Cuidado e Higiene',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 65,
              children_data: [],
            },
            {
              id: 754,
              parent_id: 397,
              name: 'Ropa para Mascotas',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 39,
              children_data: [],
            },
            {
              id: 757,
              parent_id: 397,
              name: 'Juguetes',
              is_active: true,
              position: 7,
              level: 5,
              product_count: 56,
              children_data: [],
            },
          ],
        },
        {
          id: 760,
          parent_id: 394,
          name: 'Viajes',
          is_active: true,
          position: 3,
          level: 4,
          product_count: 239,
          children_data: [
            {
              id: 763,
              parent_id: 760,
              name: 'Equipaje',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 45,
              children_data: [],
            },
            {
              id: 766,
              parent_id: 760,
              name: 'Accesorios de Viaje',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 147,
              children_data: [],
            },
            {
              id: 1150,
              parent_id: 760,
              name: 'Toallas de Playa',
              is_active: true,
              position: 4,
              level: 5,
              product_count: 47,
              children_data: [],
            },
          ],
        },
        {
          id: 772,
          parent_id: 394,
          name: 'Niños y Bebés',
          is_active: true,
          position: 4,
          level: 4,
          product_count: 71,
          children_data: [
            {
              id: 2390,
              parent_id: 772,
              name: 'Juegos y Juguetes',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 28,
              children_data: [],
            },
          ],
        },
        {
          id: 775,
          parent_id: 394,
          name: 'Jardines y Exteriores',
          is_active: true,
          position: 5,
          level: 4,
          product_count: 246,
          children_data: [
            {
              id: 778,
              parent_id: 775,
              name: 'Asadores y Parrillas',
              is_active: true,
              position: 1,
              level: 5,
              product_count: 67,
              children_data: [],
            },
            {
              id: 781,
              parent_id: 775,
              name: 'Artículos de Jardín',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 149,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 784,
      parent_id: 87,
      name: 'Temporada',
      is_active: true,
      position: 13,
      level: 3,
      product_count: 139,
      children_data: [
        {
          id: 787,
          parent_id: 784,
          name: 'Artículos de Temporada',
          is_active: true,
          position: 1,
          level: 4,
          product_count: 139,
          children_data: [
            {
              id: 793,
              parent_id: 787,
              name: 'Verano',
              is_active: true,
              position: 2,
              level: 5,
              product_count: 3,
              children_data: [],
            },
            {
              id: 799,
              parent_id: 787,
              name: 'Primavera',
              is_active: true,
              position: 3,
              level: 5,
              product_count: 2,
              children_data: [],
            },
            {
              id: 2155,
              parent_id: 787,
              name: 'Invierno',
              is_active: true,
              position: 5,
              level: 5,
              product_count: 126,
              children_data: [],
            },
            {
              id: 796,
              parent_id: 787,
              name: 'Otoño',
              is_active: true,
              position: 6,
              level: 5,
              product_count: 7,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 2567,
      parent_id: 87,
      name: 'Sin informacion',
      is_active: true,
      position: 14,
      level: 3,
      product_count: 0,
      children_data: [],
    },
  ],
};
